version: '3.7'

services:
  web:
    build: .
    volumes:
      # Uncomment for production
      # - "./docker/Caddyfile:/etc/caddy/Caddyfile"
      # Dev caddyfile
      - "./configs/caddy/local.Caddyfile:/etc/caddy/Caddyfile"
      - "caddy:/root/.caddy/"
    ports:
      # Prod ports
      # - 80:80
      # - 443:443
      - 8080:8080
    environment:
    - WWW_URL
    - ADMIN_EMAIL

volumes:
  caddy:
